# Created with YamlCreate.ps1
PackageIdentifier: silviuk.Lunifier
PackageVersion: 1.0.1
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/silviuk/Lunifier/releases/download/v1.0.1/Lunifier-Setup-1.0.1.exe
    InstallerSha256: 53E6514289E424B234CA0A01CD159B227EF345BD587CE919F869FFD21092C69B
    Scope: machine
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
