# Created with YamlCreate.ps1
PackageIdentifier: silviuk.Lunifier
PackageVersion: 2.2.1
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/silviuk/Lunifier/releases/download/v2.2.1/Lunifier-Setup-2.2.1.exe
    InstallerSha256: EA83B768AFB4B517B377C7181B37B7BE68DDAB0F311D39562BEF028F60DF2701
    Scope: machine
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
