# Created with YamlCreate.ps1
PackageIdentifier: silviuk.Lunifier
PackageVersion: 2.0.1
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/silviuk/Lunifier/releases/download/v2.0.1/Lunifier-Setup-2.0.1.exe
    InstallerSha256: 5A64A83293B0E6E544BA2BE2F6F2DB465332519A1A6737F44D78268D50148502
    Scope: machine
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
