# Created with YamlCreate.ps1
PackageIdentifier: silviuk.Lunifier
PackageVersion: 1.0.2
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/silviuk/Lunifier/releases/download/v1.0.2/Lunifier-Setup-1.0.2.exe
    InstallerSha256: BE59A5B4C8D3CE9586E9B915E6A834ACE921A218F2D30BD0F2434F1F64250654
    Scope: machine
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
